### ISSUE TITLE
Compatibility with black 19.3b0

### ISSUE THREAD

**Issue by jiafengkevinchen** [ryantam626/jupyterlab_black#14]
The following error gets thrown when one use the latest version of black. Looks like `format_str` API changed in black.
```
[E 12:05:57.351 LabApp] Uncaught exception POST /jupyterlab_code_formatter/format?1558454757345 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/jupyterlab_code_formatter/format?1558454757345', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/anaconda3/envs/py36/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/anaconda3/envs/py36/lib/python3.6/site-packages/jupyterlab_code_formatter/handlers.py", line 66, in post
        data["code"], **(data["options"] or {})
      File "/anaconda3/envs/py36/lib/python3.6/site-packages/jupyterlab_code_formatter/formatters.py", line 36, in format_code
        return format_str(code, **options)[:-1]
    TypeError: format_str() got an unexpected keyword argument 'line_length'
```
The following install statement fixes the error
`pip install black==18.9b`

**Comment by ryantam626** [comment]
Server plugin v0.2.1 with commit 512d1cd6e342c768393ede839fcc8652ab1d4a73 in it should handle this now, let me know if it doesn't :)
